import React from 'react'
import ActiveChat from './ActiveChat'

export default function Sidebar(  ) {
  return (
    <section className='w-full sm:w-2/5 h-full flex flex-col overflow-y-auto'>
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
      <ActiveChat
        targetUserName='Mau'
        profilePic=''
        lastMessage=''
      />
    </section>
  )
}
