sequenceDiagram
        Seb->>ChatDatabase: Hello Dante!
        ChatDatabase-->> Seb: Returns Updated Chat Collection
        ChatDatabase-->> Dante: Returns Updated Chat Collection
        ChatDatabase->> Dante: Hello Dante!