sequenceDiagram
%% Nodes
UserDatabase->>ChatDatabase: Create User's Collection
ChatDatabase-->>UserDatabase: Returns User Chat Collection ID for Reference

%% NewUser Function
%% Chat Interactions
%% How Users keep their chats